version: "3.7"

services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d

  php:
    volumes:
    - ./html:/var/www/html

  crond:
    volumes:
    - ./html:/var/www/html

  nginx:
    volumes:
    - ./html:/var/www/html
