definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  node__add_page:
    menu_name: tools
    parent: ''
    weight: 0
    expanded: false
    enabled: false
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
langcode: ru
